### ISSUE TITLE
Simplify local installation

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#101]
**Issue description**:
Simplify local installation
see: discussion in https://github.com/MaRDI4NFDI/portal-compose/pull/90

**TODOS**: 
- [x] update README.md
- [x] provide  easy to use install and update method or script, for local install

**Acceptance-Criteria** 
All team members should be able to install and update the system without problems.
- [ ] All containers should run (in principle)
- [ ] It should be possible to switch off the backups
- [ ] Even when the local machine is not localhost
- [ ] ?

**Checklist for this issue**: 
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by dajuno** [comment]
Some comments.

Better management of the docker-compose file could be a remedy here, cf.  #157.

Currently the docker-compose.yml is the "production" one, but it would make more sense to have a base file, the common denominator of local, CI, production, which is extended by corresponding overrides. For instance, the base file would not include backup, but backup is added by a file `docker-compose.prod.yml`. Also, the traefik host rules could be added by a production override as they make no sense on a local system. Thus the system could also run on a local system that is not localhost (by defining local traefik rules, which is impossible right now), as Alvaro suggested.

The problem of docker-compose overrides is that list items, such as volumes, ports, environments and, importantly, labels are not replaced by an override, but merged. Also it is not possible to delete items from a docker compose file, only to merge.
