### ISSUE TITLE
Select a Mediawiki layout theme

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#102]
**New feature description in words**:
Mediawiki comes with many layout themes (aka "skins"). We are using the default theme "Vector". We might find another that is more suitable for our purposes.
* https://professional.wiki/en/articles/best-responsive-mediawiki-skins
* https://www.mediawiki.org/wiki/Category:All_skins

**TODOS**: 
(In technical terms suggestions what has to be done to implement the feature.) 
- [ ] Find out requirements (responsiveness, compatibility, accessibility, maintenance...) 
- [ ] Find themes compatible with our Mediawiki version and extensions
- [ ] Install chosen theme within container docker-wikibase 
- [ ] Decide whether we want users to be able to change the theme for themselves and configure accordingly

**Considered Alternatives**: 
The current theme might not be so bad after all, we could decide to keep it.

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] MaRDI_Project has been assigned as project

**Comment by aot29** [comment]
@LizzAlice Zoom Tuesday 13:30?
