### ISSUE TITLE
Change where volumes are stored on the server

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#103]
**Issue description**:
Change where volumes are stored on the server. We have space on the disk, mounted on /srv.
But since the data is stored in Docker volumes, which is in /var/lib/docker, we have to change the place where the volumes are stored.

Adding storage space to /srv would need restarting the server, and that's too much to ask apparently. 
 
**TODOS**: 
Get required access  permissions to do that, probably docker group, maybe sudo.

in `/lib/systemd/system/docker.service`

`ExecStart=/usr/bin/dockerd --data-root /new_location/ -H fd:// $DOCKER_OPTS`

or something. See [here](https://stackoverflow.com/questions/36014554/how-to-change-the-default-location-for-docker-create-volume-command)

**Acceptance-Criteria** 
Docker volumes should show up in /srv in the Portainer Volume view.

**Checklist for this issue**: 
- [ ] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by physikerwelt** [comment]
@dajuno maybe you can have a look at this while thinking about backup?

**Comment by dajuno** [comment]
related https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/66

**Comment by eloiferrer** [comment]
Not relevant after moving to mardi02.
