### ISSUE TITLE
Document how to change passwords in our wiki

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#105]
**Issue description**:
Document how to change passwords in our wiki.

@see https://stackoverflow.com/questions/48249912/change-mysql-password-in-docker-container
 
**TODOS**: 
- [ ] How to change DB password
- [ ] How to change wiki admin password
- [ ] How to change own wiki user password
- [ ] which passwords cannot be changed

**Acceptance-Criteria** 
- [ ] Successfully change passwords above 

**Checklist for this issue**: 
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by eloiferrer** [comment]
This is documented here: https://portal.mardi4nfdi.de/wiki/Private:How_to_change_passwords
