### ISSUE TITLE
VMEXT-Demo as Rest-Endpoint for MathSearch 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#110]
**Issue description**:
- Test VMEXT instead of rest.d in combination with MathSearch extension

**TODOS**: 
- Fix dependencies in Java 
- Fix basic program so that it works with MathSearch
 

 
**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

Infos: 

 
 

 https://vmext-demo.formulasearchengine.com/swagger-ui.html#/base-x-controller 
 https://github.com/ag-gipp/vmext-demo/blob/master/src/main/java/org/citeplag/controller/BaseXController.java

**Comment by Hyper-Node** [comment]
This is done and works locally. 

Working branch can be found here: 
https://github.com/ag-gipp/vmext-demo/pull/68
