### ISSUE TITLE
Code developed in MaRDI has to be archived outside of GitHub

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#111]
**Issue description**:
Ensure that the code in the GitHub repository MaRDI4NFDI is archived outside GitHub.
 
 
**TODOS**: 

Please track every minute working on this issue.
- [ ] Understand https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/MaRDI4NFDI/portal-compose
- [ ] Deposit for example https://github.com/MaRDI4NFDI/docker-wikibase manually using the software heritage web ui
- [ ] Deposit one repository using swh save now API
- [ ] Write a script that fetches all PUBLIC github repositores from the MaRDI GitHub org (https://docs.github.com/en/rest/reference/repos) or the typscript wrapper https://github.com/bevry/github-repos
- [ ] Implement a cron /github scheduled job that fetches all repos from the MaRDI GitHub organization and saves them once a week to swh if you know typescript you can start from https://github.com/zbMATHOpen/SwhSaveNowBatch

**Acceptance-Criteria** 

- All code is backed up on software heritage.
- New code is synced with software heritage.
- New repos are backed up with software heritage
**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

Effort:
Moritz creation of the issue: 20min

**Comment by physikerwelt** [comment]
This is done. All the code is now on software heritage

* https://archive.softwareheritage.org/browse/search/?q=github.com%2Fmardi4nfdi&with_visit=true&with_content=true
* https://github.com/organizations/MaRDI4NFDI/settings/hooks/388678790
