### ISSUE TITLE
Display Twitter Timeline on MaRDI Portal

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#115]
**Issue description**:
- Twitter timeline is currently installed as an extension in the MarDI Portal
- Display a twitter newsfeed for twitter account mardi4nfdi on the main page 
-
 
 
**TODOS**: 
-  this mediawiki extension is already installed, check its functionality: https://github.com/ciencia/mediawiki-extensions-TwitterWidget
- embed html so the timeline is displayed on the right of the page
- if too many tweets limit tweets

**Acceptance-Criteria** 
- timeline displayed in described way

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by dajuno** [comment]
Done. Twitter widget was embedded in the [main page](https://portal.mardi4nfdi.de/wiki/Main_Page). No commits apply
