### ISSUE TITLE
Add functionality for embedding videos

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/portal-compose#119]
**Issue description**:
Add extension for embedding videos as described in https://www.mediawiki.org/wiki/Extension:EmbedVideo.
 
 
**TODOS**: 

- [ ] get overview
- [ ] implement

**Acceptance-Criteria** 
Videos can be embedded.

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by dajuno** [comment]
turns out I had an outdated image, pulling new images fixed the issue
