### ISSUE TITLE
traefik local config: service name conflicts

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#133]
**Issue description**:
A minor issue I encountered configuring traefik on my local machine:
Docker service names are hard coded into traefik config [traefik/conf/*.yml](https://github.com/MaRDI4NFDI/portal-compose/tree/main/traefik/conf). On my local machine the default names differ (for instance instead of `docker_whoami` I have `portal-compose-whoami`, cf also #117) from the deployed setup. Thus, the traefik routers defined in `traefik/conf` fail locally due to undefined services.
 
I think this could be easily circumvented by instead of the traefik `fileProvider` work with docker labels (apparently the use of fileProvider is somewhat discouraged and more of a legacy tool) to find and handle the services automatically.
 
**TODOS**: 

- [ ] feedback
- [ ] generalize config as to work on different machines, not only mardi server

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by dajuno** [comment]
I illustrated using labels instead of a fileprovider in pr #137, seems to be working locally. if it runs on the server is quite hard to foresee, though

**Comment by dajuno** [comment]
ok, I see. As a beginner I find the labels a little clearer and there is just a bit less to take care of, so personally I would favor labels. But it does not matter. If you really don't care I would make the pull request

**Comment by physikerwelt** [comment]
Yes. I really don't care. Go ahead.

**Comment by dajuno** [comment]
just as a side note, the "local test case" I was referring to was something like this: https://github.com/dajuno/traefik_helloworld

**Comment by physikerwelt** [comment]
Nice, I am not sure if path prefixes would work in our case. (You can even use localhost, so you don't need to change hosts). Otherwise, an option would be also to use a local resolver for development such as https://stackoverflow.com/a/51125399)
