### ISSUE TITLE
 Improve README with docker-compose overrides

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/portal-compose#157]
**Issue description**:

The readme recommends to define bash aliases for the cumbersome docker-compose commands.
IMO the better advice would be to not edit `docker-compose-dev.yml` at all, since it is version controlled, but to make a copy it to a local file named `docker-compose.override.yml`, which is not tracked and where local changes can be made.
The benefit is that docker-compose automatically reads this now [official override file](https://docs.docker.com/compose/extends/) when executing `docker-compose up -d` and `down`, `logs`, etc. (It does not use it when explicitly specifying `-f`.)
 
What do you think?

If we adopt this, it could make sense to rename the dev file for instance to `docker-compose.override.example.yml`, and the ci file to `docker-compose.ci.yml` for consistency.
 
**TODOS**: 

- [ ] edit readme
- [ ] maybe rename files

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by dajuno** [comment]
added remark on override as a hint as a compromise  #wontfix
