### ISSUE TITLE
Setup Formulasearch BaseX REST Endpoint 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#163]
**Issue description**:
VMEXT-Demo is huge, not in our repos, has no working CI builds for docker images. 
Shift it to MaRDI4NFDI enviornment and create working CI. Remove the classes from VMEXT which are not needed for formulasearch. 
 
 
**TODOS**: 

- [x] strip down  vmext-demo project 
- [x] create local docker image build 
- [x] shift repo 
- [x] create working ci build in new repo 
- [ ] add the image to portal-compose  

**Acceptance-Criteria** 
- REST API is usable in portal-compose 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
