### ISSUE TITLE
Write rest api to trigger wikidata entity import

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/portal-compose#168]
**Issue description**:
Docker importer has to trigger the wikidata entity import/update. For this purpose, a flask rest api will be created.
 
 
**TODOS**: 

- [ ] write flask script 
- [ ] put flask script in image
- [ ] trigger import from importer container

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
