### ISSUE TITLE
[Epic] Enable DFN-AAI authentication for MaRDI portal

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#192]
- [x] #282
- [x] understand  https://www.mediawiki.org/wiki/Extension:PluggableAuth maybe enable other authentication mechanisms such as with OpenID for experimentation. However, eventually editing should be restricted to users from DFN-AAI authenticated users
- [x] Determine with @ktabelow which domain name should be used for DFN-AAI
- [x] #317
- [x] Connect admins from WIAS and ZIB to transfer domain
- [x] Work with zib admin to make Shibboleth authentication with zib account work
- [x] Check performance, maybe switch mpm prefork->worker/event: https://shibboleth.atlassian.net/wiki/spaces/SHIB2/pages/2577072327/NativeSPApacheConfig

[Page for private Notes](https://portal.mardi4nfdi.de/wiki/Private:DFN-AAI)
