### ISSUE TITLE
[Epic] Formulasearch API Access

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#193]
**Issue description**:
 Instead of running on existing BaseX harvest-files and maintance scripts. Formulasearch should upgrade index with API Requests to BaseX REST API Endpoint.  

**Related Milestones**: 
- M-TA5-A5 Mathematical formula search functional

**TODOS**: 
- [x] https://github.com/MaRDI4NFDI/docker-wikibase/issues/30
- [x] #205
- [x] #206
- [x] #221
- [x] #217
- [x] #218
- [x] #222
- [x] #230
- [ ] #234
- [x] https://github.com/MaRDI4NFDI/formulasearch/issues/4
- [x] https://phabricator.wikimedia.org/T308918
- [x] https://github.com/MaRDI4NFDI/docker-wikibase/issues/38
- [x] #227
- [ ] #228
- [x] #249
- [x] #256
- [x] #258

**Acceptance-Criteria** 
- Ideally working formulasearch in portal 
- Functionality checks are passing on production 

**Functionality Checks in Production (rebased-mardi-branch for extension)**: 

- [x] Deleting Math item 'E=mc^2' on Test page after it was found by math search -> result item not found with mathsearch -> ok
- [x] Readding Math item 'E=mc^2' through edit source -> result: item is found again on page -> ok 
- [x] Moving the page which contains math item 'E=mc^2' without leaving a redirect -> item is found on new page -> ok  
- [x] Moving the page which contains math item 'E=mc^2' with a redirect ->result: item is found on new page   -> ok 
- [ ] #257
- [x] Finding formula on a page -> restarting formulasearch and mediawiki containers ->result: item is still found -> 
- [x] #260
- [x] #259
- [x] #261

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
