### ISSUE TITLE
Auto Import of external pages to mediawiki

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#202]
**Issue description**:
Write a extension script or similar which uses the externalContent Mediawiki extension to automatically import all 
markdown in a organization repository from github to mediawiki (~with prefixes in pagename).

Starting point for creation of pages could be: 
https://github.com/MaRDI4NFDI/portal-compose/tree/mirror_script
 
 
**TODOS**: 
- [ ] check most suitable method 
- [ ] implement method
 

**Acceptance-Criteria** 
- tbd 
- 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by physikerwelt** [comment]
@Hyper-Node to give this issue a chance to progress directly to the ToDo column:

Why would one want to do this?

**Comment by Hyper-Node** [comment]
Having such an extension script would enable easily to import markdown formatted data from all websites. 
I suppose many organizations (also other TA's)  have some GitHub repositories which might be linked in some form as pages in the future. 
I'd rather wait with until communication for use-case with a Task Area has been done.

**Comment by physikerwelt** [comment]
I think this script provides neither a scientific contribution leading to a publication nor serves a need we currently have. The MaRDI portal has various APIs to allow external data import. I would not invest time here. We can reopen the ticket once there is an urgent need or a novel scientific contribution connected to this effort.
