### ISSUE TITLE
Import intent XML File to Portal

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#209]
**Description**: 
Current lists of Intend Values  for MathML are formatted as xml-Files.
To reuse and reference these dictionaries for later purposes in the portal they shall be imported as wikidata entities to wikiase.

**TODOs**: 
- [ ] Get XML File with Intend Content Dictionaries  (ask @Hyper-Node or @physikerwelt for link)
- [ ] Import the Intends from level 0 to 3 as Wikidata items in the MardiPortal
- [ ] Check if openRefine can be used for that otherwise other importer ]

**Additional Info**: 

Here is a piece of javascript that ingests the spreadsheets as a
basic data structure (an Object dictionary), as part of the small demo
page made by Deyan Ginev. Here's a tiny snippet of that:
[https://github.com/dginev/tiny-mathml-a11y-demo/blob/master/assets/js/gsheets.js#L74-L79](https://deref-gmx.net/mail/client/AWI4uiSDxT8/dereferrer/?redirectUrl=https%3A%2F%2Fgithub.com%2Fdginev%2Ftiny-mathml-a11y-demo%2Fblob%2Fmaster%2Fassets%2Fjs%2Fgsheets.js%23L74-L79)

**Comment by physikerwelt** [comment]
New link https://docs.google.com/spreadsheets/d/1EsWou1K5nxBdLPvQapdoA9h-s8lg_qjn8fJH64g9izQ/edit#gid=1818558895

**Comment by Hyper-Node** [comment]
Won't do, since plan changed to chromium extension.
