### ISSUE TITLE
[Epic] Bugs

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#220]
**Issue description**:
This is an Epic to remind also to check for the noted bugs once a while in the weeklys. 
Bugs are not added specificly to the Epic atm. 
There is a bugs view in https://github.com/orgs/MaRDI4NFDI/projects/1/views/30
The bugs will be discussed by looking at this view.  

**TODOS**: 
- [ ] For each bug noted in the view identify if the bug can be a blocking bug and has to be worked on immediately. 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by eloiferrer** [comment]
No longer used or mentioned in the weeklys.
