### ISSUE TITLE
[Epic] Issues not related to Epics

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#226]
**Issue description**:
Check the issues which are not assigned to epics once a while in weekly.  
Assign them to epics if possible or mark them as bugs. 
 
This is a reminder for weekly. 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by eloiferrer** [comment]
Not used anymore in the current weekly workflow.
