### ISSUE TITLE
[Epic] Formulasearch maintenance 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#235]
**Issue description**:
Collection of future steps for adjustments to maintenance scripts in mathsearch in the portal and 
implications towards automated maintenance.
 
 

**Related Milestones**: 
- M-TA5-A5 Mathematical formula search functional

**TODOS**
(draft) 
- [ ] Fix maintenance scripts to also index Wikibase items correctly
- [ ] Fix maintenance scripts so that they are indexing all wikipage data correctly in portal
- [ ] Automated maintenance: Synchronize maintenance script usage and API based insertions to the index occuring on page-edits
