### ISSUE TITLE
List of potentially interesting MW extensions

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#243]
The purpose of this issue is to collect different extensions that might be interesting.

- [ ]  https://www.mediawiki.org/wiki/Extension:EntitySchema
- [ ] https://www.mediawiki.org/wiki/Extension:Wikispeech
- [ ] https://www.mediawiki.org/wiki/Extension:FlaggedRevs
- [ ] https://www.mediawiki.org/wiki/Extension:CiteThisPage
- [ ] https://www.mediawiki.org/wiki/Extension:PdfHandler

**Comment by Hyper-Node** [comment]
Wikispeech is indeed interesting for MathML and Accessibility,  i moved the investigation Wikispeech  to the corresponding epic.

**Comment by Hyper-Node** [comment]
Not yet, i would suggest to look at this issue in next weekly and assign them to the topic-related epics/issues then.

**Comment by physikerwelt** [comment]
I guess it is too expensive if the whole group looks at this issue. I moved the content into a comment in the epic

**Comment by Hyper-Node** [comment]
It's rather expensive to go through all comments during the meeting then click the tracked issue (because its mentioned directly in description), but anyhow this should be sufficient.

**Comment by physikerwelt** [comment]
I think the comments should only be read by the person assigned to the issue.

**Comment by Hyper-Node** [comment]
Process in the weekly meeting is this: 
- Epic gets opened
- Group looks at issues tracked in epic 
- If there is anything to discuss issue is opened and eventually updated

This makes it easier to discuss new issues in the weekly when they come as issues mentioned in the epic.

**Comment by physikerwelt** [comment]
Great. So the comment will only be considered once someone is working on the issue. This was the intention of the information shared.
