### ISSUE TITLE
[Epic] Accessibility for MathML collection

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#245]
Collection of all incoming issues and suggestions related to MathML  which are not addressed in formulasearch-epics. 
Mostly this will be related to MathML Accessibility topics. 

 
**TODOS**: 
- [x] https://github.com/MaRDI4NFDI/portal-compose/issues/209
- [x] #246
- [x] #247
- [x] reminder https://phabricator.wikimedia.org/T310249
- [ ] Enable restbase sunset https://phabricator.wikimedia.org/T302628

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by Hyper-Node** [comment]
This can be done differently and is currently drafted, since lot's of the initial design changed https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Math/+/949964
