### ISSUE TITLE
Documenting test-config workflow for development

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#276]
**Issue description**:

 We have a workflow for developing [PHP extension]( https://portal.mardi4nfdi.de/wiki/Project:Develop_and_Test_Mediawiki_Extensions_on_Production ). 
 In similar way also changing configuration in MediaWiki can be tested.
Mind here, that multiple users might override configuration. 
 
**TODOS**: 

- [ ] check proof of concept 
- [ ] document 
- [ ] eventually add files or README which describe the process 

**Acceptance-Criteria** 

- configuration can be tested with local deployment

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by Hyper-Node** [comment]
https://portal.mardi4nfdi.de/wiki/Project:Develop_and_Test_Mediawiki_Code_on_Production


Added some documentation for synchronizing LocalSettings.d folder and tested configuration deployment.
