### ISSUE TITLE
Enable syntaxhighlight

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#31]
**Issue description in words**:
Synaxhighlight should be displayed on https://portal.mardi4nfdi.de/wiki/Project:Backups
 
 
**TODOS**: 

Install https://www.mediawiki.org/wiki/Extension:SyntaxHighlight
(In technical terms suggestions what has to be done to fix the issue.) 
- Example: Modify opacity for the button-class in css files. 
-  
-  
- 

**Acceptance-Criteria** 
(what shall be reached with this issue, these criteria are mandatory for closing the issue) 
- Example: The About-button is visible when accesing home.html in Google Chrome and Firefox  
- Example: Clicking the button forwards to the 'about'-page
-

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] MaRDI_Project has been assigned as project
- [ ] code was merged to main/dev
- [ ] feature branch has been deleted after merge to main/dev
