### ISSUE TITLE
Check how Grafana Dashboard files can be tracked in repositories

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#313]
**Issue description**:
This came up during https://portal.mardi4nfdi.de/wiki/Answers_to_specific_technical_questions 
There are multiple ways and currently there is no version tracking or backup of the dashboard files which are edited in the production system. 
 
 
**TODOS**: 

- [ ] find suitable methods 
- [ ] evaluate methods 
- [ ] choose method 
- [ ] create follow up for implementation 

**Acceptance-Criteria** 

- suitable methods have been checked
- best method for mardi-portal has been chosen 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [x] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by dajuno** [comment]
https://community.grafana.com/t/grafana-dashboard-source-control/5068

**Comment by eloiferrer** [comment]
Closing this. Prometheus/Grafana work is currently tracked in: https://github.com/MaRDI4NFDI/portal-compose/issues/371
