### ISSUE TITLE
Enable uploads

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#32]
**Issue description in words**:
Uploads should be possible

 
 
**TODOS**: 

In https://portal.mardi4nfdi.de/wiki/Project:Backups I would like to upload the following pics
![Screenshot 2022-01-06 at 21-40-44 Portainer local](https://user-images.githubusercontent.com/2777736/148450442-c49bc2e7-9470-4113-a14d-f6a6054c904f.png)
![Screenshot 2022-01-06 at 21-40-20 Portainer local](https://user-images.githubusercontent.com/2777736/148450446-54100ea9-f68c-4291-9fb9-6d47c2cc3d87.png)
![Screenshot 2022-01-06 at 21-37-32 Portainer local](https://user-images.githubusercontent.com/2777736/148450448-81dbd62d-c07d-4671-8f72-744ce2327e01.png)

TODOS:

    enabling image upload in MaRDI portal
    setting up mounted folder in mediawiki
    tbc

Acceptance-Criteria

    Users can upload images to MaRDI Portal
    Images can be displayed on the pages

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] MaRDI_Project has been assigned as project
- [x] code was merged to main/dev
- [x] feature branch has been deleted after merge to main/dev

**Comment by Hyper-Node** [comment]
Just assigned this to project, it isn't visible in the planning board etc if not.

**Comment by Hyper-Node** [comment]
From alvaro: 
    also add uploads directory to backup, and mount it on the host
    might also need a graphics program like imagemagick to create the thumbnails automatically
