### ISSUE TITLE
Enable InstantCommons on the MaRDI portal wiki

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#322]
**New feature description in words**:
I would like to be able to reuse media files available on Wikimedia Commons.

As per its [description](https://www.mediawiki.org/wiki/InstantCommons), "**InstantCommons** is a feature of MediaWiki to allow the usage of any uploaded media file from the [Wikimedia Commons](https://meta.wikimedia.org/wiki/Special:MyLanguage/Wikimedia_Commons) in any MediaWiki installation world-wide."
  
 
 
**TODOS**: 
- simplest option is to just add ```$wgUseInstantCommons = true;``` to LocalSettings.php, i.e. in our case [probably](https://github.com/MaRDI4NFDI/docker-wikibase/blob/8658612e8584eda388495b3d68aee652eef11ce1/README.md#description-of-localsettingsphp-files) ```LocalSettings.php.mardi.template``` and/ or manually via the shell.

**Considered Alternatives**: 

- There are other ways to install InstantCommons, as per its description page
- We are using several ```LocalSettings.php``` files.

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] T5 Overview has been assigned as project
