### ISSUE TITLE
Install the ArticlePlaceholder extension

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#327]
**New feature description in words**:

The MediaWiki extension [ArticlePlaceholder](https://www.mediawiki.org/wiki/Extension:ArticlePlaceholder) allows to display structured data from a Wikibase instance inside a MediaWiki instance. The typical use case is a Wikipedia that does not have an entry on a given topic for which Wikidata has content.

- https://nn.wikipedia.org/wiki/Spesial:AboutTopic/Q845189
- https://cy.wikipedia.org/wiki/Special:AboutTopic/Q4454919
 
**TODOS**: 
- decide on a wiki where to test this, perhaps the portal wiki 
- decide on a namespace where to test this, perhaps not the main one (which is the default for Wikipedia et al.)
- [install it](https://www.mediawiki.org/wiki/Extension:ArticlePlaceholder#Installation) and [configure](https://www.mediawiki.org/wiki/Extension:ArticlePlaceholder#Configuration) it via LocalSettings.php 

**Considered Alternatives**: 
- 

**Checklist for this issue**: 
(Some checks for making sure this feature request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] The main MaRDI project has been assigned to this issue
