### ISSUE TITLE
Main Page Redesign 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#331]
**Issue description**:

Have 3 Fields on the main page, one for each use case 
Integrate example queries for:
- [ ] #332
- [ ] Software search e.g. swmath 
- [ ] General math search ~~~ dlmf use case atm ? 

Describe pages and their functionality with icons etc. 
(Maybe in this direction: https://www.anerkennung-in-deutschland.de/html/en/index.php# ) 

**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
Main Page redesign will be part of the new Skin development.
