### ISSUE TITLE
[Epic][Draft] MaRDI Portal API 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#337]
**Epic description in words**:
  
Creating an API for accessing MaRDI-Portal components and data. 
Defining the public and internal interfaces. 
Practically, there are some components of Wikibase which already have GUI interfaces (like quickstatements and openrefine), writing API endpoints for them is probably not necessary, however we could forward some of their capabilities to our API endpoints if they will be extensively used. For other libraries and implemented components we could have an access point API, example an API before (Wikidata Integrator, Wikibase Integrator etc. ) which offers the public capabilities used in our scenario. 

This is a very early WIP-draft. 

**Tentative Tasks**: 

1. Check if Python or PHP is suitable  (KG API is PHP)
2. Collection of use-cases and possible endpoints
3. Forward the KG API, check how this can be done with open-api specification

**Preliminary feature ideas:**  
- Authentication
- Some security layer, especially for the public endpoints 
- ORM Mapping to Data in MediaWiki / Wikibase 
- Swagger features: API Documentation has only be noted on one point, automated client generation. 
- Jupyter Notebooks integration somehow
- Forwarding SPARQL Request for KG Queries 
- Messaging System, queues for more time-consuming jobs 
- Microservice architecture 
- Common techniques for creating 'federated' API's
- Ingest integration 
- Import an Entity from Wikidata by API call to Portal KG 

**Additional Info**:
 
- https://www.mediawiki.org/wiki/API:REST_API
- https://www.mediawiki.org/wiki/Wikibase/API
- https://github.com/shigapov/wikibase-knowledge-graphs#the-wikibase-api-and-wrappers
 
**Corresponding Milestones**: 
  
- A3, D3, A4a

 
**Epic issues**: 
  
- [ ] issue one github-link  
- [ ] ...

**Related bugs**: 
  
- 

**Epic acceptance criteria**: 
  
- [ ] first criterion 

**Checklist for this epic**: 
- [x] the main MaRDI project has been assigned as project
- [ ] report has been created 

![apidraft2](https://user-images.githubusercontent.com/8139033/214312585-88fdc918-599e-48cc-8d2c-bdf3f9307f07.png)

**Comment by Hyper-Node** [comment]
This will be done at a later stage, currently we can use Wikibase/Mediawiki API's directly at some point if we have more API features, we add the currently specified requests to this Portal-API. @eloiferrer
