### ISSUE TITLE
[Epic][Draft] Include clinical data into knowledge graph

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/portal-compose#340]
**Epic description in words**:
Clinical data sources (e.g. proteomics) should be included into knowledge graph

 
**Epic issues**: 

- [ ] Create a list of possible data sources
- [ ] Check licensing to narrow down possible imports
- [ ] Write modules to import these data sources

**Comment by eloiferrer** [comment]
Not in the plan currently. Eventually move it into docker-importer.
