### ISSUE TITLE
[Epic][Draft] Machine learning on knowledge graphs

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/portal-compose#341]
**Epic description in words**:
Machine learning on knowledge graph for edge prediction

 
**Epic issues**: 
  
- [ ] Evaluate machine learning methods for relation prediction
- [ ] (Look into other usecases, evaluate these)
- [ ] Implement preferred method on subset
- [ ] Test preferred method on whole graph, if this makes sense

**Comment by eloiferrer** [comment]
Closing epic. Being reformulated by @LizzAlice.
