### ISSUE TITLE
[Epic] Provide a set of feature queries

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#345]
**Epic description in words**:

This epic is to provide a set of queries that demonstrate technical features of the query infrastructure or the data types.

**Additional Info**:

Feature queries require at least the following
- a queriable database with well-defined data structures 
- some data in that database
- some feature to demonstrate
- some interface to send queries to the database and receive a response
- relevant permissions

They serve several purposes
- documenting, testing and teaching some aspects of the infrastructure
- documenting, testing and teaching some aspects of the data
- paving the way towards useful queries as per ############# and federated queries as per #############
 
**Corresponding Milestones**: 

- M-TA5-A3 API access possible.
- M-TA5-A4 Math specific data-types implemented.
- M-TA5-A5 External identifiers integrated.
- M-TA5-C1 Ontologies implemented.
- M-TA5-C2 MaRDI metadata standard for scientists and publications established.
- M-TA5-C3 MaRDI metadata standard for software and institutions established.

 
**Epic issues**: 
  
- [ ] issue one Github-link  
- [ ] ...

**Related bugs**: 
  
- 

**Epic acceptance criteria**: 

- [ ] At least one feature query for each implemented data type, along with suitable documentation.
- [ ] At least one feature query for each implemented external identifier, along with suitable documentation.
- [ ] A mechanism that regularly checks that the queries perform as documented.

**Checklist for this epic**: 
- [ ] the main MaRDI project has been assigned as project
- [ ] report has been created
