### ISSUE TITLE
[Epic] Provide a set of useful queries

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#346]
**Epic description in words**:

This epic is to provide a set of queries that yield data that can be readily incorporated into mathematical research and teaching workflows.

**Additional Info**:

Useful queries require at least the following
- a use case, e.g. a research question or a teaching point
- functional query infrastructure, as demonstrated via feature queries (cf. #345)
- data relevant to the use case
- documentation of query elements that are relevant to the example use case
- documentation of aspects of the query that may need adaptation for other use cases
- reproducibility, including in the context of dynamic data
- citability of the queries
- citability of the results
- provisions for data curation
- provisions for query curation

They serve several purposes
- documenting, testing, teaching and possibly advancing some aspects of mathematics, including relevant data, software or infrastructure
 
**Corresponding Milestones**: 

- M-TA5-A3 API access possible.
- M-TA5-A4 Math specific data-types implemented.
- M-TA5-A5 External identifiers integrated.
- M-TA5-C1 Ontologies implemented.
- M-TA5-C2 MaRDI metadata standard for scientists and publications established.
- M-TA5-C3 MaRDI metadata standard for software and institutions established.
- M-TA5-C4 Process documentation on MSC assignment to MaRDI artifacts established.
 
**Epic issues**: 
  
- [ ] issue one Github-link  
- [ ] ...

**Related bugs**: 
  
- 

**Epic acceptance criteria**: 

- [ ] A set of at least 10 example use cases, of which at least 6 for research and at least 1 for teaching.
- [ ] At least one useful query for each use case, along with suitable documentation.
- [ ] For each useful query, one example of how it can be adapted to serve use cases that differ in specific ways.
- [ ] A mechanism that regularly checks that the queries perform as documented.
- [ ] Some mechanism allowing users to subscribe to some aspects of useful queries, e.g. dynamic changes to the results.

**Checklist for this epic**: 
- [ ] the main MaRDI project has been assigned as project
- [ ] report has been created
