### ISSUE TITLE
[Epic] Provide a set of federated queries

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#347]
**Epic description in words**:

This epic is to test setup, workflows and use cases for designing, running, sharing and improving federated queries, i.e. queries that involve the MaRDI portal as well as at least one other resource.

**Additional Info**:

Federated queries require at least the following
- a useful intersection of data between the resources that are to be combined
- data structures and metadata standards that are compatible at least for that intersection
- performant infrastructure with established communication protocols between the two sides
- relevant permissions on both ends

 
**Corresponding Milestones**: 

- M-TA5-A6 Federated NFDI queries possible.

 
**Epic issues**: 
  
- [ ] issue one Github-link  
- [ ] ...

**Related bugs**: 
  
- 

**Epic acceptance criteria**: 

- [ ] Federation to at least one other NFDI endpoint enabled
- [ ] Federation to at least one non-NFDI endpoint enabled
- [ ] Federation from at least one other NFDI endpoint enabled
- [ ] Federation from at least one non-NFDI endpoint enabled
- [ ] A set containing at least one federated query example for each endpoint with which federation is enabled. These queries should be useful in the sense of ticket #346.

**Checklist for this epic**: 
- [ ] the main MaRDI project has been assigned as project
- [ ] report has been created
