### ISSUE TITLE
Install the MediaWiki Extension Wikibase Export

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#349]
**New feature description in words**:
 
The new MediaWiki Extension [Wikibase Export](https://www.mediawiki.org/wiki/Extension:Wikibase_Export) provides a non-SPARQL mechanism to export simple subsets of the data in a given Wikibase.

The primary use case motivating its development was exporting longitudinal social science data from BERD@NFDI by year, for which we have not much need. However, the extension is configurable for more complex use cases, and its SPARQL independence is interesting in terms of performance, so I think it would be useful for us to give the extension a closer look.

**TODOS**: 
-  [x] install the extension as per https://www.mediawiki.org/wiki/Extension:Wikibase_Export/en
-  [ ] test, configure and document as necessary

**Considered Alternatives**: 

- The main alternatives are dumps, SPARQL endpoints and the MediaWiki API. Depending on the specific use cases, some, all or none of these alternatives may be suited better or worse than this extension.

**Checklist for this issue**: 
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] The main MaRDI project has been assigned to this issue

**Comment by physikerwelt** [comment]
This is a bit difficult, as the extension is not stored in gerrit and thus works orthogonal to the regular update procedure. I'll try anyhow.

**Comment by physikerwelt** [comment]
cf. https://github.com/MaRDI4NFDI/docker-wikibase/commit/bf08990e7ea308d9582fcd50262468407782fc03

**Comment by physikerwelt** [comment]
it worked better than expected

![Screenshot 2023-02-21 at 19-37-03 MaRDI portal](https://user-images.githubusercontent.com/2777736/220431140-ee57b02f-5abc-4237-a099-f5a9f20d7a55.png)

**Comment by physikerwelt** [comment]
so now we have the latest base image and the extension is fetched. Let's what happens, if we enable it.
![Screenshot 2023-02-21 at 20-22-13 MaRDI portal](https://user-images.githubusercontent.com/2777736/220439320-e59d4093-c76d-4a18-b46a-2ca5e055e585.png)

**Comment by physikerwelt** [comment]
Installation is complete. I leave testing to @Daniel-Mietchen 
![Screenshot 2023-02-21 at 20-29-47 Version - MaRDI portal](https://user-images.githubusercontent.com/2777736/220440712-22f61993-9b8c-460c-a97d-8e2605f6d4a6.png)

**Comment by Daniel-Mietchen** [comment]
Thanks, @physikerwelt !

Some initial observations:
- the page https://portal.mardi4nfdi.de/wiki/Special:WikibaseExport exists 
  - it says that it can be configured via https://portal.mardi4nfdi.de/wiki/Special:WikibaseExportConfig but that is a redirect to [MediaWiki:WikibaseExport](https://portal.mardi4nfdi.de/wiki/MediaWiki:WikibaseExport), which is empty.
    - Some notes related to that are in https://github.com/ProfessionalWiki/WikibaseExport#php-configuration .
  - the "entities to export" field is not reactive to input (I tried strings like "P2" and "DMLF id" and "Q1" and "DLMF:1.2.E1")

Perhaps @JeroenDeDauw can advise, or perhaps update the documentation?

**Comment by physikerwelt** [comment]
@Daniel-Mietchen thank you. Just a note on the configuration:

The configuration can be changed by editing

https://github.com/MaRDI4NFDI/portal-compose/blob/main/mediawiki/LocalSettings.d/WikibaseExport.php

This can be done directly from within the browser.

This is basically equivalent to LocalSettings.php. However, it does not seem to require configuration?

**If there is anything you think I can do to help, let me know and assign me please.**

**Comment by JeroenDeDauw** [comment]
> it says that it can be configured via https://portal.mardi4nfdi.de/wiki/Special:WikibaseExportConfig but that is a redirect to [MediaWiki:WikibaseExport](https://portal.mardi4nfdi.de/wiki/MediaWiki:WikibaseExport), which is empty.

Interesting, you have found a way to improve usability of the configuration page :)

It is expected that said page is empty if there is no config. Once you edit it, you will get placeholder config and documentation.

Next time we create such an extension, we hope to have a sufficient budget to create a form-based interface for the config rather than requiring the editing of JSON.

**Comment by eloiferrer** [comment]
The extension is correctly installed. 
If there are further configuration requirements we can open a new issue.
I am closing this for now.
