### ISSUE TITLE
Change default locations for wd and wdt prefies in query.portal.mardi4nfdi.de

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#36]
In the query:
```SPARQL
PREFIX wdt: <https://portal.mardi4nfdi.de/prop/direct/>
PREFIX wd: <https://portal.mardi4nfdi.de/entity/>
SELECT ?item ?dlmfid ?formula
WHERE {?item wdt:P4 wd:Q1750 .
         OPTIONAL{?item wdt:P2 ?dlmfid .}
                OPTIONAL{?item wdt:P14 ?formula .}      

      }
Limit 10
```
the first two lines should not be required.

**Expected behavior**
```SPARQL
SELECT ?item ?dlmfid ?formula
WHERE {?item wdt:P4 wd:Q1750 .
         OPTIONAL{?item wdt:P2 ?dlmfid .}
                OPTIONAL{?item wdt:P14 ?formula .}      

      }
Limit 10
```
Should result in the same result as the first query.

**To Reproduce**
Go the https://query.portal.mardi4nfdi.de paste the query and see the result. (Direct link https://tinyurl.com/y2l6pmtt)

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by physikerwelt** [comment]
Does this still need clarification?

**Comment by physikerwelt** [comment]
@Hyper-Node clear now?

**Comment by Hyper-Node** [comment]
yes

**Comment by physikerwelt** [comment]
@eloiferrer are you still working on this?

**Comment by physikerwelt** [comment]
maybe this is https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Configurable_properties wikibaseConceptUri

**Comment by eloiferrer** [comment]
I haven't checked this in a while. The problem seemed to be related to the http/https connection from inside the container. But maybe we can test this now in staging with wikibaseConceptUri.

**Comment by eloiferrer** [comment]
This has been now fixed with https://github.com/MaRDI4NFDI/srv-mardi02/commit/4767a276b1c0a9c9bcc8bccc7e309ca0f3381a59
