### ISSUE TITLE
Restore alerts in prometheus and dashboards in grafana

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#371]
**Issue description**:
- Alerts and dashboards were lost when moving to the new server and have to be added again manually.
- Grafana dashboards were backed up as json, but prometheus needs to be configured before they can be restored.
- Alerts also have to be created again, for the following cases:
  - Portal is down
  - Scholia is down
  - Blazegraph synchronizer is down
  - Back up failed 

 
**TODOS**: 
- [ ] Configure prometheus metrics
- [ ] Setup alerts
- [ ] Restore dashboards from .json files
- [ ] Track grafana dashboard and configuration in github (see https://github.com/mpostument/grafana-sync and https://github.com/Beam-Connectivity/grafana-dashboard-manager)
- [ ] Remove current dashboard backup script (after implementation of github synchronization)

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [x] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by LizzAlice** [comment]
- [ ] Get dashboards running:
    - [ ] Backup monitor
    - [ ] node exporter
    - [ ] traefik
    - [ ] traefik 2
    - [ ] watchtower
- [ ]  configure email alerts
    - [ ] portal down
    - [ ] scholia down
    - [ ] blazegraph synchronizer down
    - [ ] back up failed

**Comment by eloiferrer** [comment]
This is now obsolete.
Monitoring for the Kubernetes cluster is being tracked at https://github.com/MaRDI4NFDI/portal-k8s/issues/6
