### ISSUE TITLE
Do not restart wikibase automatically

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#376]
**Issue description**:

Restarting containers can lead to an unresponsive portal, so this should be done manually.
 
**TODOS**: 

- [ ] [Change watchtower to pull but not restart containers ](https://containrrr.dev/watchtower/arguments/#without_restarting_containers)

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
