### ISSUE TITLE
Check if logrotate is configured in mardi02

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#385]
**Issue description**:
Check whether the logrotate configuration for traefik has been propertly configured in the new server.
Specifically: https://github.com/MaRDI4NFDI/portal-compose/blob/main/traefik/logrotate.conf
 
 
**TODOS**: 
- [ ] Copy the logrotate.conf file to /etc/logrotate.d/traefik in mardi02

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
This is not relevant anymore
