### ISSUE TITLE
Run portal-compose locally

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#41]
**Issue description in words**:
(What is the reason for creating the issue and what is it about)  
For development and further purposes, it is required to run portal-compose locally
 
 
**TODOS**: 
(In technical terms, suggestions of what has to be done to fix the issue.) 
- Example: Modify opacity for the button-class in CSS files. 
-  fix docker setup on PC (also without sudo) 
-  setup env file 
- docker compose 

**Acceptance-Criteria** 
- local instance running 

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] MaRDI_Project has been assigned as project

**Comment by Hyper-Node** [comment]
Done, in env file removed all URL statements: 

`
## Wikibase Configuration
WIKIBASE_PINGBACK=false
# wikibase.svc is the internal docker hostname, change this value to the public hostname
WIKIBASE_HOST=192.168.178.21
WIKIBASE_PORT=8050

## WDQS-frontend Configuration
# wdqs.formulasearchengine.com
WDQS_FRONTEND_HOST=wdqs.formulasearchengine.com
WDQS_FRONTEND_PORT=8035

## Quickstatements Configuration
# wdqs.quickstatements.com
QUICKSTATEMENTS_HOST=wdqs.quickstatements.com
QUICKSTATEMENTS_PORT=8036

WB_PUBLIC_HOST_AND_PORT=192.168.178.21:8840
QS_PUBLIC_HOST_AND_PORT=192.168.178.21:8834

## ElasticSearch
MW_ELASTIC_HOST=192.168.178.21
MW_ELASTIC_PORT=8037
`
