### ISSUE TITLE
Create sample content

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#411]
**Issue description**:

 Currently, the portal starts empty. This is not optimal for development and testing. Therefore, we should create a minimal subset that can be used to test the portal functionalities.
 
**TODOS**: 

- [ ] create a list of pages that are mutually different and represent a good variety of what is included in the MaRDI portal
- [ ] export this list of pages as XML file and import it during test run

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
