### ISSUE TITLE
Investigate Extensions in local Setup 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#42]
**Issue description in words**:
(What is the reason for creating the issue and what is it about)  
To know the extensions and their usage and modifcation, investigate these in local setup. 
 
**TODOS**: 
(In technical terms, suggestions of what has to be done to fix the issue.) 
- Check extensions,
- Read about extensions 
- Have a look on implementation 
- Check the main functionality wihtin the wiki 

**Acceptance-Criteria** 
(what shall be reached with this issue, these criteria are mandatory for closing the issue) 
- At least Math and MathSearch extensions checked 

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] MaRDI_Project has been assigned as project

**Comment by aot29** [comment]
Regarding putting extensions in the Dockerfile or not:

Here is an example of a Dockerfile with a fetcher container (this is an older version of quickstatements, lines 1-15): https://github.com/MaRDI4NFDI/docker-quickstatements/blob/e5e7eda10c0043dac156de9f6bf302755101dbe6/Dockerfile 

Note that if the extensions are copied into the Dockerfile, then the wikibase and the backup container volumes in docker-compose have to be edited.

I would be in favor of putting extensions in the Dockerfile, since the volume mounts in the backup service are very complex now (shared volume with mounted extensions that point to submodules).

**Comment by Hyper-Node** [comment]
Some examples for pagedits with math-ml, at the moment the tex-based-representation is rendered.
`

<math>3 + 2 </math>

Presentation Math:  
<math><mi>x</mi><mo>=</mo></math>

Content Math: 
<math><mrow><apply> <eq/> <apply> <plus/> <apply> <power/> <ci>x</ci> <cn>2</cn> </apply> <apply> <times/> <cn>4</cn> <ci>x</ci> </apply> <cn>4</cn> </apply> <cn>0</cn></apply></mrow></math>

Texstyle 

<math>A \in B </math>

Texstyle 2 

<math>\frac{n!}{k!(n-k)!} = \binom{n}{k}</math>


`
