### ISSUE TITLE
Add descriptions & references to zenodo datasets

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/portal-compose#437]
**Issue description**:
Add long description as a string for the zenodo datasets that were already imported from the mardigmci community (https://zenodo.org/communities/mardigmci?q=&l=list&p=1&s=10&sort=newest)

Some descriptions seem to include references to citations. The metadata for this publications could also be added. 
 
**TODOS**: 
- [ ] Create description property for long strings
- [ ] Check whether description can be obtained through the zenodo API, otherwise parse it.
- [ ] Insert the description in the existing items
- [ ] Insert references to publications

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
Description, references and license information has been added: https://tinyurl.com/yqtrgzwd
The description property for long descriptions has been created: https://portal.mardi4nfdi.de/wiki/Property:P1457
