### ISSUE TITLE
MathSearch - Implement MathSearch Prerequisites in portal-compose

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#47]
**New feature description in words**:
(What is the new feature about and why is it beneficial to the users)  
  For using MathSearch-Extension and also BaseX installation implementation of MWS has to be connected to MediaWiki.
  Also Genshi extension seems to be required. 

From [MWS-documentation](https://www.mediawiki.org/wiki/Extension:MathSearch)
$wgMWSUrl: The link to your (local) MathWeb Search installation e.g. "http://localhost:8090";
$wgMathSearchBaseX: The link to your (local) BaseX installation e.g. "http://localhost:10043"; 
 

**TODOS**: 
(In technical terms suggestions what has to be done to implement the feature.) 
- Clarify with @physikerwelt which prerequisites are required currently
- Create appropriate docker containers which install prerequisites  for MathSearch with docker-compose

**Acceptance-Criteria**: 
- After docker-compose setup, the MWS and BaseX installation are running and properly connected to the main-container. 
- MathSearch is indexing pages and results are returned. 

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] MaRDI_Project has been assigned as project

**Comment by Hyper-Node** [comment]
@physikerwelt this is still to be clarified, it could also be that description in documentation is obsolete: https://www.mediawiki.org/wiki/Extension:MathSearch 


or the MWS and BaseX installations are located elsewhere and not in mardi-portal container setup.

**Comment by physikerwelt** [comment]
The instructions seem to be fine. It is still something to be done while not very urgent.
I think https://hub.docker.com/r/mathwebsearch/mathwebsearch and https://hub.docker.com/r/basex/basexhttp might do the job in a docker environment. Only the configuration needs to be adjusted in that case. Feel free to edit https://www.mediawiki.org/wiki/Extension:MathSearch and add yourself as a maintainer.

**Comment by physikerwelt** [comment]
@Hyper-Node this is still in clarification mode. Can we move it to todo?

**Comment by Hyper-Node** [comment]
Yes, moved.

**Comment by Hyper-Node** [comment]
Since MWS isn't functional out of the box, directly checking BaseX

**Comment by Hyper-Node** [comment]
BaseX with rest.d ok except rendering. Follow Up:

**Comment by Hyper-Node** [comment]
https://github.com/MaRDI4NFDI/portal-compose/issues/110
