### ISSUE TITLE
Add author names

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/portal-compose#487]
**New feature description in words**:
Some (a lot) authors don't have proper names in the MaRDI portal. The goal is to add names to the authors.
  
 
 
**TODOS**: 
(In technical terms, suggestions what has to be done to implement the feature.) 
-  For all authors with zbMATH Id the name can be obtained from api.zbmath.org
-  Map fields of the API to fields in Wikibase
- Find a label for authors. This is a bit tricky as the name is Last, First but not First Last. However, the title of the website uses the following code to do the conversion
```python
    item = g.result["hits"]["hits"][0]["_source"]
    g.page_title = "{name} - Author Profile".format(
        name=" ".join(
            reversed(
                [
                    name_part.strip()
                    for name_part in item["name"].split(
                        ",",
                        maxsplit=1
                    )
                ]
            )
        )
```

**Checklist for this issue**: 
(Some checks for making sure this feature request is completely formulated)
- [ ] Participants in discussion have been invited as assignees (cc @LizzAlice , @timconrad )
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] The main MaRDI project has been assigned to this issue

**Comment by LizzAlice** [comment]
Can it be acquired over the api though? Because the names were not always returned when I queried the papers.

**Comment by physikerwelt** [comment]
See for example https://portal.mardi4nfdi.de/wiki/Item:Q2740228 no name is given.  However https://api.zbmath.org/v1/author/yaroshko.s-a gives
```JSON
{
  "result": {
    "aliases": [],
    "awards": [],
    "code": "yaroshko.s-a",
    "collective_of": [],
    "external_ids": [],
    "further_spellings": [],
    "id": 676403,
    "main_fields": [
      {
        "count": 2,
        "field": "45",
        "percent": "28.571428571428573",
        "percentile": "28.571428571428573"
      },
      {
        "count": 2,
        "field": "65",
        "percent": "28.571428571428573",
        "percentile": "57.142857142857146"
      }
    ],
    "in_collective": [],
    "name": "Yaroshko, S. A.",
    "reviewer": null,
    "spellings": [
      {
        "count": 5,
        "first_name": "S. A.",
        "initials": "S A",
        "last_name": "Yaroshko",
        "name": "Yaroshko, S. A."
      }
    ],
    "states": [],
    "zbmath_url": "https://zbmath.org/authors/yaroshko.s-a"
  },
  "status": {
    "execution": "successful request",
    "execution_bool": true,
    "internal_code": "ok",
    "query_execution_time_in_seconds": 0.04577136039733887,
    "status_code": 200,
    "time_stamp": "2024-02-08 15:35:26.767660"
  }
}
``` which is equivalent to `item = g.result["hits"]["hits"][0]["_source"]` in the code above.

**Comment by eloiferrer** [comment]
The addition of labels has finished. All zbMath authors have a label now.

**Comment by physikerwelt** [comment]
Amazing, one little request regariding our strategic goal documentation. Can you link the code and your notes (if you have) or an excerpt from your bash history here. I suggest to timebox this activity with 15min.
