### ISSUE TITLE
On person profiles, add panel for resources used

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#497]
**New feature description in words**:
(What is the new feature about and why is it beneficial to the users)  
 
On a page like https://portal.mardi4nfdi.de/wiki/Person:1739017 , a panel (similar to 
https://scholia.toolforge.org/author/Q37391308#use )
should be added to show software associated with that person, e.g. [DROPS](https://portal.mardi4nfdi.de/wiki/Item:Q24749), which is [stated as having been used](https://portal.mardi4nfdi.de/wiki/Item:Q1739018#P1463) in [A penalty finite element method for a fluid system posed on embedded surface](https://portal.mardi4nfdi.de/wiki/Publication:1739018).

**TODOS**: 
(In technical terms, suggestions what has to be done to implement the feature.) 
-  Extend Template person with a query similar to https://github.com/WDscholia/scholia/blob/master/scholia/app/templates/author_use.sparql .

**Considered Alternatives**: 
(Alternatives which have been considered for this feature) 
- The status quo, which is not to show the resources used.

**Checklist for this issue**: 
(Some checks for making sure this feature request is completely formulated)
- [X ] Participants in discussion have been invited as assignees 
- [X] All fields of the issue have been filled 
- [X] Example fields have been removed
- [X] The main MaRDI project has been assigned to this issue
