### ISSUE TITLE
Enable federated queries to the FactGrid SPARQL endpoint

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#534]
**New feature description in words**:
Add 
https://database.factgrid.de/sparql
to the allowlist of external SPARQL endpoints.  
 
 
**TODOS**: 
- [x]   Find the allowlist --> https://github.com/wmde/wikibase-release-pipeline/blob/main/build/WDQS/allowlist.txt
- [x] add https://database.factgrid.de/sparql
- [x] Find prefix lists (e.g. https://github.com/MaRDI4NFDI/srv-mardi02/blob/main/portal-compose-override/wdqs/prefixes.conf )
- [x] add FactGrid prefixes, modeled after the Wikidata ones (e.g. PREFIX FactGrid: <https://database.factgrid.de/sparql>)
- [x] deploy on staging
- [ ] deploy on production

**Checklist for this issue**: 
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] The main MaRDI project has been assigned to this issue

**Comment by physikerwelt** [comment]
Eventually, it was [successfully deployed](https://github.com/MaRDI4NFDI/srv-mardi03/actions/runs/9256347977/job/25463235841) Could you please test it on https://query.staging.mardi4nfdi.org/

**Comment by physikerwelt** [comment]
It was good that we tested this, as there were several roadblocks in the context of the allowlist, and the 15-minute task eventually took a full hour.

**Comment by Daniel-Mietchen** [comment]
Thanks &mdash; [https://query.staging.mardi4nfdi.org/#%23defaultView%3AMap%0A%0APREFIX%20FactGrid_wd%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fentity%2F%3E%0APREFIX%20FactGrid_wdt%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fprop%2Fdirect%2F%3E%0A%0ASELECT%20DISTINCT%20%3Fmathematician%20%3FmathematicianLabel%20%3FaddressLabel%20%3Fcoord%20WHERE%20%7B%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fsparql%3E%20%7B%0A%0A%20%20%20%20SELECT%20%3Fmathematician%20%3FmathematicianLabel%20%3FaddressLabel%20%3Fcoord%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20WHERE%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fmathematician%20FactGrid_wdt%3AP2%20FactGrid_wd%3AQ7%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20FactGrid_wdt%3AP165%2FFactGrid_wdt%3AP3%2a%20FactGrid_wd%3AQ152945%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20FactGrid_wdt%3AP208%20%3Faddress.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Faddress%20FactGrid_wdt%3AP47%20FactGrid_wd%3AQ10441%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20FactGrid_wdt%3AP48%20%3Fcoord.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20limit%20100%20%20%7D%0A%7D%0A works fine] on the staging server:

```SPARQL
#defaultView:Map

PREFIX FactGrid_wd: <https://database.factgrid.de/entity/>
PREFIX FactGrid_wdt: <https://database.factgrid.de/prop/direct/>

SELECT DISTINCT ?mathematician ?mathematicianLabel ?addressLabel ?coord WHERE {
  SERVICE <https://database.factgrid.de/sparql> {

    SELECT ?mathematician ?mathematicianLabel ?addressLabel ?coord
                          WHERE 
                          {
                            ?mathematician FactGrid_wdt:P2 FactGrid_wd:Q7;
                                           FactGrid_wdt:P165/FactGrid_wdt:P3* FactGrid_wd:Q152945;
                                           FactGrid_wdt:P208 ?address.
                            ?address FactGrid_wdt:P47 FactGrid_wd:Q10441;
                                     FactGrid_wdt:P48 ?coord.
                            SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } 
                          }
    limit 100  }
}
```

![Screenshot 2024-05-27 at 20-50-20 MaRDIQueryService](https://github.com/MaRDI4NFDI/portal-compose/assets/465923/9262f299-8427-4721-a8e6-06888bd3e9f4)

**Comment by physikerwelt** [comment]
Ok, then, let's move on to production.

**Comment by physikerwelt** [comment]
Works as well in production https://tinyurl.com/2aebroao

**Comment by Daniel-Mietchen** [comment]
Yep. Now we can make the list of prefixes more complete.

**Comment by physikerwelt** [comment]
@Daniel-Mietchen yes. All we need is  a list in the form

PREFIX FactGrid: https://database.factgrid.de/sparql

Maybe we can also develop a generic test query that can be applied to all endpoint, just to check if the connection works.

**Comment by physikerwelt** [comment]
PS: For staging, the list can be directly edited on github and will be immediately deployed.

https://github.com/MaRDI4NFDI/srv-mardi03/blob/main/portal-compose-override/wdqs/prefixes.conf
