### ISSUE TITLE
Case-normalize DOIs in the portal graph

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MaRDI4NFDI/portal-compose#594]
**Issue description**:

DOIs in the portal are currently not case normalized, so we have some that are [all-lowercase](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5Ba-z%5D%22%29%0A%20%20FILTER%20%28%21REGEX%28%3Fdoi%2C%20%22%5BA-Z%5D%22%29%29%0A%7D%0ALIMIT%201000), some [all-uppercase](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5BA-Z%5D%22%29%0A%20%20FILTER%20%28%21REGEX%28%3Fdoi%2C%20%22%5Ba-z%5D%22%29%29%0A%7D%0ALIMIT%201000) and some that have [both lower-and uppercase characters](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5Ba-z%5D%22%29%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5BA-Z%5D%22%29%0A%20%20FILTER%20%28%21REGEX%28%3Fdoi%2C%20%22arXiv%22%29%29%0A%7D%0ALIMIT%201000). Special cases exist, e.g. arXiv DOIs usually contain the string [```arXiv```](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20%28REGEX%28%3Fdoi%2C%20%22arXiv%22%29%29%0A%7D%0ALIMIT%2010000) as such, while we currently have [one case](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q6527230&oldid=38004382#P27) of [```arxiv```](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20%28REGEX%28%3Fdoi%2C%20%22arxiv%22%29%29%0A%7D%0ALIMIT%201000) and none for [```ARXIV```](https://tinyurl.com/25vofxv2).

This complicates things like duplicate detection, and a straightforward fix would be to simply case-normalize DOIs. Wikidata uses uppercase normalization (as recommended by Crossref), so I suggest we go with that too.
 
**TODOS**: 

- [x] get list of [items with DOIs that have lower-case characters](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5Ba-z%5D%22%29%0A%7D%0ALIMIT%20100000)
- [x] uppercase-normalize these DOI strings
- [x] replace non-normalized string with normalized one

**Acceptance-Criteria** 

- [x] A maintenance query for [DOIs with lower-case characters](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5Ba-z%5D%22%29%0A%7D%0ALIMIT%2010) yields zero results

**Checklist for this issue**: 
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project

**Comment by physikerwelt** [comment]
Ok

**Comment by physikerwelt** [comment]
Starting this now

**Comment by Daniel-Mietchen** [comment]
One thing I forgot to mention above is to adapt the import scripts accordingly.
Pinging @LizzAlice @eloiferrer .

**Comment by LizzAlice** [comment]
Got it, thank you!

**Comment by physikerwelt** [comment]
Some progress https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MathSearch/+/1100858 it took much longer than one hour (as I would have expected)

**Comment by physikerwelt** [comment]
I did run it on a small number of examples.

https://portal.mardi4nfdi.de/wiki/Special:Contributions/Import241208021249

@Daniel-Mietchen, please review it before we run it for all DOIs.

**Comment by Daniel-Mietchen** [comment]
@physikerwelt These sample edits look god, but perhaps the selection of test items should have been based on a more random sample, e.g. as per https://tinyurl.com/2alh6ol9

**Comment by physikerwelt** [comment]
thank you @Daniel-Mietchen

**Comment by physikerwelt** [comment]
Now the full run started see https://portal.mardi4nfdi.de/w/index.php?title=User:Import241208061232 

1.2M lowercase links to go...

**Comment by physikerwelt** [comment]
wdqs reports 1.3 M links to go https://tinyurl.com/289lmyc3

**Comment by Daniel-Mietchen** [comment]
The updater does not seem to pick up the changes yet. For instance, [Q894330](https://portal.mardi4nfdi.de/wiki/Item:Q894330) has had its normalization edit [over 15 min ago](https://portal.mardi4nfdi.de/w/index.php?title=Item:Q894330&diff=prev&oldid=38525155), yet a [query for its DOI](https://query.portal.mardi4nfdi.de/#SELECT%20%3Fdoi%20WHERE%20%7B%0A%20%20wd%3AQ894344%20wdt%3AP27%20%3Fdoi%20%0A%7D) still yields the lower-case value.

**Comment by physikerwelt** [comment]
The updater picks up changes, but it seems that not all changes are picked up. It would be interested to see if it picks up all changes that do appear in the recent-changes log.

**Comment by physikerwelt** [comment]
Another problem is that this is incredibly slow. We just made 480k changes, and it's been running for over a day.

**Comment by Daniel-Mietchen** [comment]
Still 886069 DOI normalization edits [to be made](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5Ba-z%5D%22%29%0A%7D%0ALIMIT%201000000):

![grafik](https://github.com/user-attachments/assets/db4b5a00-0148-416f-914c-0cc81a1a727b)

**Comment by physikerwelt** [comment]
I had to stop the price since it might have slowed down the server.  Before continuing I think it would also be good to trigger a blazegraph resync instead of null edits.

**Comment by physikerwelt** [comment]
I looked at examples and realized that some items have two dois. I added the handling of those to those

https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MathSearch/+/1107043/1/includes/Graph/Job/NormalizeDoi.php

and improved the server performance a bit so that it was possible to restart the process.

**Comment by physikerwelt** [comment]
Once the job is done, I'll use the query to get a list qIDs to update the items in blazegraph.

**Comment by physikerwelt** [comment]
I fixed the example Q894344 by running 
```
docker exec docker-wdqs-1 bash -c '/wdqs/runUpdate.sh -h http://${WDQS_HOST}:${WDQS_PORT} -- --wikibaseUrl ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --conceptUri ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --entityNamespaces ${WDQS_ENTITY_NAMESPACES} --ids Q894344 --start 20150211170100'
```
see https://portal.mardi4nfdi.de/wiki/Project:RerunUpdate

**Comment by physikerwelt** [comment]
With the sparql query
```SPARQL
PREFIX wdt: <https://portal.mardi4nfdi.de/prop/direct/>
SELECT ?qid WHERE {
  BIND (REPLACE(STR(?item), "^.*/(Q[^/]*)$", "$1") as ?qid) .
  ?item wdt:P27 ?doi .
  FILTER REGEX(?doi, "[a-z]")
}
LIMIT 10
```
one can get all ids and put that into the command. This gives
```
mardi-test-user@mardi02:~$ docker exec docker-wdqs-1 bash -c '/wdqs/runUpdate.sh -h http://${WDQS_HOST}:${WDQS_PORT} -- --wikibaseUrl ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --conceptUri ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --entityNamespaces ${WDQS_ENTITY_NAMESPACES} --ids Q2920277,Q61738,Q61749,Q61791,Q62047,Q62241,Q62290,Q62650,Q63513,Q63543 --start 20150211170100'
Updating via http://wdqs.svc:9999/bigdata/namespace/wdq/sparql
#logback.classic pattern: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
10:04:19.777 [main] INFO  org.wikidata.query.rdf.tool.Update - Starting Updater 0.3.137 (1ac054ca5bfa49a6f743c581decf5c9be649f455)
10:04:22.952 [main] INFO  org.wikidata.query.rdf.tool.Updater - Polled up to 9 at (0.0, 0.0, 0.0) updates per second and (0.0, 0.0, 0.0) ids per second

**Comment by physikerwelt** [comment]
The same method works for 10 000 but that seems to be the limit for cli, thus we need to write a small bash script

**Comment by physikerwelt** [comment]
ChatGPT suggests
```bash
#!/bin/bash

# Path to the input CSV file
INPUT_FILE="input.csv"

# Number of rows to process at a time
CHUNK_SIZE=1000

# Docker command template
DOCKER_CMD_TEMPLATE="docker exec docker-wdqs-1 bash -c '/wdqs/runUpdate.sh -h http://${WDQS_HOST}:${WDQS_PORT} -- --wikibaseUrl ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --conceptUri ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --entityNamespaces ${WDQS_ENTITY_NAMESPACES} --start 20150211170100 --ids {IDS}'"

# Temporary file to hold chunks
temp_chunk="chunk.tmp"

# Read the file in chunks of 1000 lines
split -l $CHUNK_SIZE "$INPUT_FILE" "$temp_chunk"

for file in ${temp_chunk}*; do
    # Concatenate the rows with commas (remove newlines)
    IDS=$(tr '\n' ',' < "$file" | sed 's/,$//')

    # Replace {IDS} in the command template with the concatenated IDs
    CMD=${DOCKER_CMD_TEMPLATE//\{IDS\}/$IDS}

    # Execute the command
    echo "Running command: $CMD"
    eval $CMD

    # Clean up the temporary chunk file
    rm -f "$file"
done

# Clean up the temporary file if it exists
rm -f "$temp_chunk"

**Comment by physikerwelt** [comment]
In the end, I could not make chatgpt to fix the script. Thus I fixed it myself
```
#!/bin/bash

# Path to the input CSV file
INPUT_FILE="input.csv"

# Number of rows to process at a time
CHUNK_SIZE=1000


# Temporary file to hold chunks
temp_chunk="chunk.tmp"

# Read the file in chunks of 1000 lines
split -l $CHUNK_SIZE "$INPUT_FILE" "$temp_chunk"

for file in ${temp_chunk}*; do
    # Concatenate the rows with commas (remove newlines)
    IDS=$(tr '\n' ',' < "$file" | sed 's/,$//')

    docker exec docker-wdqs-1 bash -c '/wdqs/runUpdate.sh -h http://${WDQS_HOST}:${WDQS_PORT} -- --wikibaseUrl ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --conceptUri ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --entityNamespaces ${WDQS_ENTITY_NAMESPACES} --start 20150211170100 --ids '"$IDS" 

    # Clean up the temporary chunk file
    rm -f "$file"
done

# Clean up the temporary file if it exists
rm -f "$temp_chunk"

**Comment by physikerwelt** [comment]
wdqs reports 0.4 M links to go https://tinyurl.com/289lmyc3

the update script seems to be complete. I'll check some examples

**Comment by physikerwelt** [comment]
I checked 10 examples and all 10 contain lowercase chars.

**Comment by Daniel-Mietchen** [comment]
I checked 5 edits - all looks fine.

**Comment by Daniel-Mietchen** [comment]
> Once the job is done, I'll use the query to get a list qIDs to update the items in blazegraph.

The Blazegraph update should probably go beyond the QIDs touched in this batch. For instance, those from https://portal.mardi4nfdi.de/wiki/Special:Contributions/Import241212081232 do not seem to have been updated there either.

**Comment by physikerwelt** [comment]
> > Once the job is done, I'll use the query to get a list qIDs to update the items in blazegraph.
> 
> The Blazegraph update should probably go beyond the QIDs touched in this batch. For instance, those from https://portal.mardi4nfdi.de/wiki/Special:Contributions/Import241212081232 do not seem to have been updated there either.

Does this relate to this issue?

**Comment by physikerwelt** [comment]
I restarted the script for the remaining 30k.

**Comment by Daniel-Mietchen** [comment]
I am reopening this, as we have accumulated 88k [lower-case DOIs again](https://query.portal.mardi4nfdi.de/#SELECT%20%2a%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP27%20%3Fdoi%20.%0A%20%20FILTER%20REGEX%28%3Fdoi%2C%20%22%5Ba-z%5D%22%29%0A%7D%0ALIMIT%20100000): 

![Image](https://github.com/user-attachments/assets/be1ab184-6a2c-4a67-84af-039e03a8bc87)

**Comment by Daniel-Mietchen** [comment]
Also pinging @LizzAlice @eloiferrer to check the importers.

**Comment by LizzAlice** [comment]
We are lower case normalizing the dois in the scripts, I have the feeling that fact got lost somewhere in communication

**Comment by physikerwelt** [comment]
No, it should be uppercase as shown in the examples.

**Comment by physikerwelt** [comment]
Fixing via
```
 root@78af6054bc16:/var/www/html/w# ./maintenance/run ./extensions/MathSearch/maintenance/Properties.php case-normalize
Read from offset 0.

**Comment by physikerwelt** [comment]
26 740 / 87000 ... some progress.

**Comment by physikerwelt** [comment]
69 883 edits  no more jobs

**Comment by physikerwelt** [comment]
@eloiferrer it seems that the graph is out of sync. Would it make sense to resync, or is the transition to k8n close?

**Comment by eloiferrer** [comment]
Sorry this is taking longer that I expected.

One the one hand it is close considering that [https://staging.mardi4nfdi.org/](https://staging.mardi4nfdi.org/) is fully migrated with all the core services running already on the cluster. It is great news that things are very stable on that end.

On the other, I've hit some serious issues to figure out how to load our production database and getting it replicated over the other instances + learning how to recover in case of failure. I think I am very close to getting this right.

Once this is ready it will be fast to make the switch, the bottleneck has really been the production DB. I really hope I can get it done throughout next week.

**Comment by eloiferrer** [comment]
I am looking into this now.

I assume running something like:
```
/wdqs/runUpdate.sh -h http://${WDQS_HOST}:${WDQS_PORT} -- --wikibaseUrl ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --conceptUri ${WIKIBASE_SCHEME}://${WIKIBASE_HOST} --entityNamespaces ${WDQS_ENTITY_NAMESPACES} --start 20150211170100
```
won't work because we have partially already erased the Recent Changes list.

The alternative is running [dumpRDF](https://doc.wikimedia.org/Wikibase/master/php/docs_topics_rdf-binding.html) and load it then to Kubernetes. Do you have experience with this script? I am afraid I might crash mardi02 if I try to run it.

**Comment by physikerwelt** [comment]
I think many of the maintenance scripts have now also been optimized for k8n use see https://phabricator.wikimedia.org/T341560
