### ISSUE TITLE
Provide Wikibase Docker image with standard extensions preinstalled

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#61]
**Issue description**:
The image should be built from an official image that receives updates.

Extensions that we will not be contributing to, i.e.
* JsonConfig
* Lockdown
* TemplateStyles
 should be placed inside the wikibase container. This will make sure several errors don't happen, including crashing the server when a new extension is introduced as a submodule, but not initialized when pulled to the server by the cronjob.
 
**TODOS**: 
* [x] Create new project docker-wikibase
* [x] Docker FROM clause should use only official Images
* [x] Add extensions to Dockerfile in docker-wikibase (everything version 1.35 for now), applying fetcher pattern
* [x] Add docker-wikibase image to all 3 docker-compose files
* [x] make sure corresponding extensions are not mounted from host (wikibase, backup),
* [x] CI-actions

**Acceptance-Criteria** 
* [x] all extensions are listed in Version page (there's a test for that)
* [x] the server doesn't crash when cronjob pulls the changes

**Checklist for this issue**: 
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [x] Code was merged
- [x] Feature branch has been deleted and issues were updated / closed

**Comment by physikerwelt** [comment]
If we build a new MediaWiki container, we should probably not use the Wikibase base container, but rather the official MediaWiki container to get updates more easily. What do you think?

**Comment by aot29** [comment]
We are currently unable to add extensions to the server instance. This is a workaround for that problem. So it's urgent. I would rather build the image based on the bundle to take pressure off the problem, and then rebuild the image from the official container as another ticket: update all containers, migrate the data.

**Comment by physikerwelt** [comment]
We can just change the update command on the server in 10 minutes. So we already have a workaround. Thus, I would advocate to build the new image not under great time pressure and rather aim for a sustainable solution.

**Comment by Hyper-Node** [comment]
Yes, i think this is suitable for the moment.

**Comment by aot29** [comment]
OK then. When you merge the feature-user-documentation branch (with Lockdown extension), you'll have to do on the host `git submodule update --init` and perhaps `docker exec -ti mardi-wikibase php maintenance/update.php` as well (but I'm not sure about that).
I don't think you want to add this to the update command, as it runs 1 x minute though.

**Comment by Hyper-Node** [comment]
Checking git submodule status and update conditionally within the update command might be workaround.

**Comment by aot29** [comment]
Better solution by @hyper-node

**Comment by aot29** [comment]
**Current status is:**
* There's a Dockerfile in its own project: https://github.com/MaRDI4NFDI/docker-wikibase
* All extensions are now included in the image, which simplifies docker-compose a lot. It's still possible to mount custom extensions on top of them.
* The portal can be started using docker-compose in the branch https://github.com/MaRDI4NFDI/portal-compose/tree/wikibase_docker_image
* All tests pass

**To do:**
* Container now builds from the base wikibase image from wmde (not from the bundle), it should be built from the official mediawiki image 

**Before attempting to merge**
* Make sure that the update works without deleting volumes first (if not, which ones) as LocalSettings is mounted as a volume on the current portal installation
