### ISSUE TITLE
Evaluate OpenRefine to reformat data for import

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#65]
**New feature description in words**:
Examine how OpenRefine can be used to import data into Wikibase / Quickstatements
 
**TODOS**: 
* [ ] Read documentation

**Considered Alternatives**: 
* [ ] Simply import a CSV file

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] MaRDI_Project has been assigned as project
