### ISSUE TITLE
Documentation overview improvements 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#67]
**Issue description**:
Documentation will grow, the overview page https://portal.mardi4nfdi.de/wiki/Project:Documentation_Overview has to be modified for each new page manually. 
In the future, something like Extension:DynamicPageList might make sense to make the pages appear automatically on the overview page.
 
 
**TODOS**: 

- Check most suitable solution 
- Implement solution 

**Acceptance-Criteria** 
- Solution implemented 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by Hyper-Node** [comment]
@aot29 maybe theres a standard functionality for this

**Comment by aot29** [comment]
> @aot29 maybe theres a standard functionality for this

Can't do that with the standard functionality. But I would use SemanticMediawiki rather than DynamicPageList. SemanticMediawiki has  a lot of functionality (forms, templates, stored queries) that we could use, if we manage to connect it to our Wikibase. See one discussion [here](https://www.quora.com/To-implement-a-new-easy-to-use-semantic-MediaWiki-based-internal-knowledgebase-should-I-implement-Wikibase-or-Semantic-Mediawiki-Why). @physikerwelt what do you think?

**Comment by physikerwelt** [comment]
See https://portal.mardi4nfdi.de/w/index.php?title=Project%3ADocumentation_Overview&type=revision&diff=103093&oldid=103082 for my proposal of a solution.

**Comment by Hyper-Node** [comment]
> See https://portal.mardi4nfdi.de/w/index.php?title=Project%3ADocumentation_Overview&type=revision&diff=103093&oldid=103082 for my proposal of a solution.

i think this solves this issue for now.
