### ISSUE TITLE
Show image thumbnails 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#68]
**Issue description**:
For the images, also thumbnails get shown correctly. 
  https://github.com/MaRDI4NFDI/portal-compose/issues/32
 
 
**TODOS**: 
(In technical terms, suggestions what has to be done to implement the feature.) 
-  Create installation script for ImageMagick so that it is automatically deployed to the 
-  
- 

**Acceptance-Criteria** 

- Thumbnails showing up correctly on portal mardi 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
