### ISSUE TITLE
[Epic] Fancy Portal Features Collection 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#70]
**Issue description**:
This is an epic for collecting simple frontend tasks which are for optimizing the public display of the mardi-portal. 
 
 
**TODOS**: 
- Embedded Videos - https://www.mediawiki.org/wiki/Extension:EmbedVideo 
- Show Tweets in a timeline, something like this or just embedded html: - https://www.mediawiki.org/wiki/Extension:Social_Sidebar
- Custom design (looks like default MediaWiki atm), maybe something that corresponds to the overall MaRDI pages design, https://www.mediawiki.org/wiki/Manual:Skinning_Part_1 
- There is also responsive design skins: https://www.mediawiki.org/wiki/Manual:Mobiles,_tablets_and_responsive_design 
- If tweet timeline not enough, some blog-style functionality for the front pages 
- visualization of the database content which can be presented on the front pages 
- Some content: More descriptions, Someday: An introduction video which shows the current progress
- https://www.mediawiki.org/wiki/Extension:S5SlideShow Adding powerpoint/Slides to pages. 
- Mirroring Github pages in Mediawiki. https://github.com/MaRDI4NFDI/portal-compose/pull/87
- Spam prevention measures. 
- https://github.com/MaRDI4NFDI/portal-compose/issues/243
- [x]   https://www.mediawiki.org/wiki/Extension:EntitySchema
- [ ]  https://www.mediawiki.org/wiki/Extension:FlaggedRevs
- [ ]  https://www.mediawiki.org/wiki/Extension:CiteThisPage
- [ ]  https://www.mediawiki.org/wiki/Extension:PdfHandler

**Acceptance-Criteria** 
- collect possible improvements 
- if necessary create further issues  

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by aot29** [comment]
Some examples from previous projects (Internet archive)
* https://web.archive.org/web/20211129162323/https://biowikifarm.net/v-mfn/panda/
* https://web.archive.org/web/20160506164035/https://biowikifarm.net/v-mfn/arbeitstagung2015/
* https://web.archive.org/web/20160823113636/http://biowikifarm.net/v-mfn/sammlung/Hauptseite

**Comment by Hyper-Node** [comment]
For Twitter: <div class="thumb tright" style="width:350px;height:500px">
<twitter account="Hyper_Node" tweet-limit=3 />
</div>

**Comment by Hyper-Node** [comment]
https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/33

**Comment by physikerwelt** [comment]
Additional features that might be of interest


> 
>     * [ ]   https://www.mediawiki.org/wiki/Extension:EntitySchema
> 
>     * [x]   https://www.mediawiki.org/wiki/Extension:Wikispeech
> 
>     * [ ]  https://www.mediawiki.org/wiki/Extension:FlaggedRevs
> 
>     * [ ]  https://www.mediawiki.org/wiki/Extension:CiteThisPage
> 
>     * [ ]  https://www.mediawiki.org/wiki/Extension:PdfHandler

**Comment by physikerwelt** [comment]
I will remove https://www.mediawiki.org/wiki/Extension:Slides as this is unmaintained. I hope it was not used for anything

**Comment by eloiferrer** [comment]
I removed the Twitterwidget extension since we cannot activate it directly for users due to DSGVO

**Comment by physikerwelt** [comment]
As stated in the issue description
> if necessary create further issues
