### ISSUE TITLE
Mirror Mediawiki Pages from  Github

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#77]
**Issue description**:
Develop a script that updates the wikitext in the portal with content defined in GitHub
 
**TODOS**: 

One might follow the implementation from the DRMF project

This page

https://github.com/DRMF/operations-puppet-drmf/blob/master/files/drmf.wiki

is written to that location

https://drmf-beta.wmflabs.org/wiki/Project:About

by the following script

https://github.com/DRMF/operations-puppet-drmf/blob/ab9a24aace044a085a2c0a55e5eef9bb752e725a/manifests/roles/drmf.pp#L133-L135

which effectively does

https://github.com/wikimedia/mediawiki-vagrant/blob/d69f56d00699eafb7da8cd268b43e5aafae86afb/puppet/modules/mediawiki/manifests/import/text.pp#L64

To simplify the process, we could map an entire folder and write a small script that processes the entire folder. We can run the script together with the container that runs the regular update.php jobs

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by physikerwelt** [comment]
@Hyper-Node is this clear now?

**Comment by Hyper-Node** [comment]
@physikerwelt is it the idea that a MediaWiki VM with vagrant is set up, so that puppet script can do consistent modifications? 
Or can the puppet scripts be directly connected to MediaWiki-Docker?

**Comment by physikerwelt** [comment]
No, I would just call edit.php with a small shell script.

**Comment by Hyper-Node** [comment]
Done and deployed.

**Comment by Hyper-Node** [comment]
Follow up: https://github.com/MaRDI4NFDI/portal-compose/issues/202
