### ISSUE TITLE
Cleanup old images from production environment

### ISSUE THREAD

**Issue by aot29** [MaRDI4NFDI/portal-compose#85]
**New feature description in words**:
In the portainer, you can see that there are images that are not used. Can we delete these?  Can we do this automatically?
 
**TODOS**: 
- Go to: https://portainer.portal.mardi4nfdi.de/#!/2/docker/images 
- the unused backup and quickstatements images can be deleted
- what about the other unused images, can we delete these too?

**Considered Alternatives**: 
As watchtower pulls new images automatically, we should consider automatic cleanup of "dangling" images, to avoid clogging disk space on the server.

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [x] Participants in discussion have been invited as assignees 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] MaRDI_Project has been assigned as project

**Comment by aot29** [comment]
What do you think?

**Comment by physikerwelt** [comment]
Sure, you can clean the containers. However, there is also the option --remove-orphans which should do most of the work automatically. I guess it is a better investment of our time to talk to @timconrad and ask for more disk space, as to spend a lot of time with cleanup tasks.

**Comment by physikerwelt** [comment]
I checked the link. There were only very few containers.
![grafik](https://user-images.githubusercontent.com/2777736/152327339-aed87d3d-75e7-4e54-8873-b8ae5d5939b3.png)
So remove-orphans seems to work. I cleaned the current containers and don't think that further action is required.

**Comment by aot29** [comment]
Old images are not removed. Portainer doesn't seem to have a --remove-orphans settings. I don't know how to change the portal-compose (if that's where this option is supposed to go).

**Comment by physikerwelt** [comment]
I see only three unused images. I think this is as good as it can get.

**Comment by aot29** [comment]
OK
