### ISSUE TITLE
Create MaRDI Dienstag Presentation

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#88]
**Issue description**:
Create presentation 
 
**TODOS**: 

- [x] Obtain Presentation Template slides 
- [x] Create Presentation 
- [x] Synchronize with Team for Content
- [x] Present
- [x] Store presentation somewhere available for team 

**Acceptance-Criteria** 
- Presentated at MaRDI Dienstag a

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [x] Issue has been estimated

**Comment by Hyper-Node** [comment]
stored in cloud.mardi4nfdi
