### ISSUE TITLE
Math Search Investigation

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#89]
**Issue description**:
Math Search Sachen ankucken Lokal zum Laufen bringen (BaseX extension etc.)
 
Use BaseX and Extension.

**TODOS**: 
- Check extensions 
- Run and Deploy locally 
- Check what to do with them 
- tbd more items

**Acceptance-Criteria** 
-tbc

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [x] Issue has been estimated

**Comment by Hyper-Node** [comment]
https://github.com/MaRDI4NFDI/portal-compose/issues/47
