### ISSUE TITLE
Fix maintenance scripts in MathSearch extension

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#91]
**Issue description**:
Running the maintenance scripts (update.php, createMWSHarvest.php)  raises some errors, which have been partially fixed locally. With this issue the errors shall be tackled. 
 
**TODOS**: 
- [ ] Fix dependencies to other extensions like Math and Mathoid
- [ ] Fix obsolete code which causes errors in maintenance scripts 

**Acceptance-Criteria** 
- Scripts are running and search-index can be created 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

Info: 
- tbd paste info about namespaces and references in extension.json
