### ISSUE TITLE
Create IDE with PhP-Storm and Debugging for MWS-Extensions

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/portal-compose#92]
**Issue description**:
Checking maintenance scripts clarified that there will be probably more php-development for formulasearch.  Therfore IDE shall and environment shall be set up correctly. 
 
 
**TODOS**: 

- [x] enable docker container with debugging 
- [x] Get PHPStorm and set it up for debugging
- [x] import extensions which are changed as repositories (not submodules) so they can be modified. 

**Acceptance-Criteria** 
- TODOS completed, local debugging is possible

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated

**Comment by Hyper-Node** [comment]
Done, documented in Portal-Compose README, with url to extended doku in portal wiki.
